### ISSUE TITLE
Semangat gan, Challenge Go nya

### ISSUE THREAD

**Issue by ghost** [R1dwanMaulana/Challenge-Golang#1]
Sekedar referensi :book: , semoga bermanfaat :
- [Banyuwangi Dev, Golang](https://github.com/banyuwangidev/golang)
- [Daspro Golang, Noval Agung](https://dasarpemrogramangolang.novalagung.com/)
- [Awesome Go](https://github.com/avelino/awesome-go)

Kalau males ngoding ? digenerate aja :gear: 
- [paich](https://github.com/onigura/paich)

**Comment by R1dwanMaulana** [comment]
Ok thank you bro👍🏻
